  bryanMvc[m
  develop[m
  express[m
  feature/bryan-mvc[m
  feature/cadastro[m
  feature/emerson-mvc[m
* [32mfeature/home[m
  feature/listagem-produto[m
  feature/login[m
  feature/mcvo[m
  feature/mvc[m
  feature/produto[m
  feature/rafaela-mvc[m
  feature/registro[m
  feature/usuario[m
  featureCarrinhoProduto[m
  ht-mobile[m
  listagem-produtos[m
  main[m
  module[m
  product[m
  proot[m
  [31mremotes/github/HEAD[m -> github/main
  [31mremotes/github/bryanMvc[m
  [31mremotes/github/develop[m
  [31mremotes/github/feature/bryan-mvc[m
  [31mremotes/github/feature/cadastro[m
  [31mremotes/github/feature/emerson-mvc[m
  [31mremotes/github/feature/home[m
  [31mremotes/github/feature/listagem-produto[m
  [31mremotes/github/feature/login[m
  [31mremotes/github/feature/mcvo[m
  [31mremotes/github/feature/mvc[m
  [31mremotes/github/feature/produto[m
  [31mremotes/github/feature/rafaela-mvc[m
  [31mremotes/github/feature/registro[m
  [31mremotes/github/feature/usuario[m
  [31mremotes/github/featureCarrinhoProduto[m
  [31mremotes/github/listagem-produtos[m
  [31mremotes/github/main[m
